# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSImmSaYZI71CK9ySsHHb5iV5MjeXUBP
"""



import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 1. Load dataset
df = pd.read_csv("heart.csv")

X = df.drop("target", axis=1)   # Features
y = df["target"]               # Label

# 2. Feature Scaling (ML preprocessing)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# 3. Split data (ML training/testing)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# ------------------ ML STARTS HERE ------------------

# 4. Create ML model
model = LogisticRegression()

# 5. Train ML model (Learning step)
model.fit(X_train, y_train)   # 👈 THIS IS WHERE ML HAPPENS

# 6. Make predictions
y_pred = model.predict(X_test)

# 7. Evaluate model
print("Accuracy:", accuracy_score(y_test, y_pred))

"""# New Section"""